/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#2a1700",
        "error": "#ffb4ab",
        "on-background": "#dde2f3",
        "surface-container": "#1a202c",
        "secondary-fixed-dim": "#ffb95f",
        "error-container": "#93000a",
        "secondary-fixed": "#ffddb8",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#89f5e7",
        "on-primary-fixed": "#410002",
        "surface-dim": "#0e131f",
        "surface": "#0e131f",
        "inverse-surface": "#dde2f3",
        "on-tertiary-container": "#ddfff9",
        "on-secondary": "#472a00",
        "on-tertiary-fixed-variant": "#005049",
        "tertiary-fixed-dim": "#6bd8cb",
        "tertiary-container": "#008075",
        "on-secondary-fixed-variant": "#653e00",
        "on-primary-container": "#fff6f5",
        "surface-container-lowest": "#080e1a",
        "primary": "#ffb4ab",
        "secondary": "#ffb95f",
        "surface-bright": "#343946",
        "on-error": "#690005",
        "surface-variant": "#2f3542",
        "background": "#0e131f",
        "inverse-on-surface": "#2b303d",
        "surface-container-highest": "#2f3542",
        "on-primary": "#690005",
        "outline-variant": "#5c403c",
        "on-tertiary": "#003732",
        "on-surface-variant": "#e6bdb8",
        "primary-fixed": "#ffdad6",
        "surface-container-high": "#242a36",
        "inverse-primary": "#bf0715",
        "surface-tint": "#ffb4ab",
        "primary-container": "#dc2626",
        "on-primary-fixed-variant": "#93000b",
        "surface-container-low": "#161c28",
        "on-surface": "#dde2f3",
        "primary-fixed-dim": "#ffb4ab",
        "outline": "#ac8884",
        "on-secondary-container": "#5b3800",
        "tertiary": "#6bd8cb",
        "secondary-container": "#ee9800",
        "on-tertiary-fixed": "#00201d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        "unit": "4px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk"],
        "data-display": ["JetBrains Mono"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "data-label": ["JetBrains Mono"],
        "headline-lg": ["Hanken Grotesk"]
      }
    },
  },
  plugins: [],
};
